[project]
requires-python = ">=3.10"
name = "attila"
version = "2.0.0"
description = "Attila Pelican Theme"
authors = [{ name = "Arulraj Venni", email = "me@arulraj.net" }]
maintainers = [{ name = "Wei Lee", email = "weilee.rx@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }

keywords = ["pelican", "pelican-theme", "markdown", "theme", "python", "ghost"]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Plugins",
  "Environment :: Web Environment",
  "Framework :: Pelican :: Themes",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: JavaScript",
  "Programming Language :: Other",
  "Programming Language :: Python :: 3",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Text Processing :: Markup :: HTML",
  "Topic :: Text Processing :: Markup :: Markdown",
]

dependencies = [
  "pelican >= 4.0.0",
  "pelican-image-process >= 3.0.0",
  "pelican-minify >= 2.0.0",
  "pelican-neighbors >= 1.2.0",
  "pelican-related-posts >= 1.0.0",
  "pelican-seo >= 1.2.0",
  "pelican-sitemap >= 1.2.0",
  "pelican-statistics >= 1.0.0",
  "pelican-webassets >= 2.1.0",
]

[dependency-groups]
dev = [
    { include-group = "base" },
    { include-group = "test" },
    { include-group = "linters" },
]
base = ["poethepoet>=0.34.0"]
test = ["pytest>=9.0.0", "BeautifulSoup4"]
linters = ["ruff>=0.15.4"]

[project.urls]
"Homepage" = "https://github.com/Lee-W/attila"
"Documentation" = "https://github.com/Lee-W/attila"
"Repository" = "https://github.com/Lee-W/attila"
"Issues" = "https://github.com/Lee-W/attila/issues"
"Releases" = "https://github.com/Lee-W/attila/releases"

[build-system]
requires = ["uv_build >= 0.10.3, <0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pelican.themes.attila"
module-root = "src"

[tool.poe]
[tool.poe.tasks]
format.help = "Format the code"
format.sequence = [{ cmd = "ruff check --fix" }, { cmd = "ruff format" }]

lint.help = "Lint the code"
lint.sequence = [{ cmd = "ruff check" }]

check-commit.help = "Check the commit messages"
check-commit.cmd = "cz --no-raise 3 check --rev-range origin/main.."

test.help = "Run the test suite"
test.cmd = "pytest"

all.help = "Run all tasks"
all.sequence = ["format", "lint", "check-commit", "test"]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
